"""Initial migration

Revision ID: 56e1da36b519
Revises: 
Create Date: 2025-03-29 12:48:55.329136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56e1da36b519'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric', schema=None) as batch_op:
        batch_op.add_column(sa.Column('memory_info', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('disk_usage', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric', schema=None) as batch_op:
        batch_op.drop_column('disk_usage')
        batch_op.drop_column('memory_info')

    # ### end Alembic commands ###
